# Create new tag
POST http://localhost:3333/api/tags HTTP/1.1
Content-Type: application/json

{
  "title": "books"
}
###

# Get all tags
GET http://localhost:3333/api/tags HTTP/1.1
###

# Get tag by ID
GET http://localhost:3333/api/tags/1 HTTP/1.1
###

# Delete tag
DELETE http://localhost:3333/api/tags/1 HTTP/1.1
###
